#!/bin/bash
#This script was generated by Speckle gen_binaries.sh
echo 'Running: ./x264_r_base.riscv-64 --pass 1 --stats x264_stats.log --bitrate 1000 --frames 1000 -o BuckBunny_New.264 BuckBunny.yuv 1280x720'
./x264_r_base.riscv-64 --pass 1 --stats x264_stats.log --bitrate 1000 --frames 1000 -o BuckBunny_New.264 BuckBunny.yuv 1280x720
echo 'Running: ./x264_r_base.riscv-64 --pass 2 --stats x264_stats_copy.log --bitrate 1000 --dumpyuv 200 --frames 1000 -o BuckBunny_New.264 BuckBunny.yuv 1280x720'
./x264_r_base.riscv-64 --pass 2 --stats x264_stats_copy.log --bitrate 1000 --dumpyuv 200 --frames 1000 -o BuckBunny_New.264 BuckBunny.yuv 1280x720
echo 'Running: ./x264_r_base.riscv-64 --seek 500 --dumpyuv 200 --frames 1250 -o BuckBunny_New.264 BuckBunny.yuv 1280x720'
./x264_r_base.riscv-64 --seek 500 --dumpyuv 200 --frames 1250 -o BuckBunny_New.264 BuckBunny.yuv 1280x720
